import mongoose from "mongoose";

const AnalysisReportSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  originalFilename: { 
    type: String, 
    required: true 
  },
  filePath: { 
    type: String, 
    required: true 
  }, 
  
  // Path to the PDF generated by AI
  generatedReportPath: {
    type: String
  },

  // NEW: Stores the "Database Context" discovered by the AI
  collectionInsight: {
    totalDocs: { type: Number, default: 0 },
    contextDescription: { type: String, default: "" }, // e.g., "Mostly Financial Statements"
    fileTypes: [{ type: String }]
  },

  status: { 
    type: String, 
    enum: ['pending', 'processing', 'completed', 'failed'], 
    default: 'pending' 
  },

  // Structured AI Analysis
  analysisResult: {
    summary: { type: String, default: "" },
    keywords: [{ type: String }],
    trends: [{ type: String }],
    decisions: { type: String, default: "" }, 
    finalReportText: { type: String, default: "" } 
  },

  uploadDate: { 
    type: Date, 
    default: Date.now 
  }
});

const AnalysisReport = mongoose.model('AnalysisReport', AnalysisReportSchema);

export default AnalysisReport;